// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-my-progress.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/supabase-client.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.0";
function supabaseAsUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function isAdmin(ctx) {
  const supabase = supabaseAsUser(ctx);
  const { data, error } = await supabase.rpc("has_role", {
    _user_id: ctx.getUserId(),
    _role: "admin"
  });
  if (error) return false;
  return Boolean(data);
}

// src/lib/mcp/tools/get-my-progress.ts
var get_my_progress_default = defineTool({
  name: "get_my_progress",
  title: "Meu progresso na NachesU",
  description: "Lista as eletivas em que o estudante est\xE1 matriculado, m\xF3dulos conclu\xEDdos, pr\xF3ximo m\xF3dulo e progresso por trilha.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "n\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseAsUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: enrollments }, { data: progress }] = await Promise.all([
      supabase.from("enrollments").select("id, course_id, status, created_at, courses(id, slug, title)").eq("user_id", userId),
      supabase.from("student_module_progress").select("module_id, status, updated_at").eq("user_id", userId)
    ]);
    const payload = {
      email: ctx.getUserEmail(),
      enrollments: enrollments ?? [],
      module_progress: progress ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-modules.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var list_modules_default = defineTool2({
  name: "list_modules",
  title: "Listar m\xF3dulos liberados",
  description: "Lista m\xF3dulos + p\xEDlulas de uma eletiva. Respeita `module_releases`: s\xF3 retorna m\xF3dulos que j\xE1 foram liberados pela turma.",
  inputSchema: {
    course_slug: z.string().min(1).describe("slug da eletiva, ex: 'ia-na-pratica' ou 'economia-circular'"),
    include_pills: z.boolean().default(false).describe("se true, inclui as p\xEDlulas de cada m\xF3dulo")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ course_slug, include_pills }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "n\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseAsUser(ctx);
    const { data: course, error: courseErr } = await supabase.from("courses").select("id, slug, title, description").eq("slug", course_slug).maybeSingle();
    if (courseErr || !course) {
      return {
        content: [{ type: "text", text: `eletiva '${course_slug}' n\xE3o encontrada` }],
        isError: true
      };
    }
    const select = include_pills ? "id, number, title, summary, trail_id, module_pills(id, kind, title, duration_min, order_index)" : "id, number, title, summary, trail_id";
    const { data: modules, error } = await supabase.from("modules").select(select).eq("course_id", course.id).order("number");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const payload = { course, modules: modules ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/submit-evidence.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var submit_evidence_default = defineTool3({
  name: "submit_evidence",
  title: "Registrar evid\xEAncia de m\xF3dulo",
  description: "Envia o registro/s\xEDntese do PBL de um m\xF3dulo em nome do estudante. Grava em `module_deliverables` respeitando RLS.",
  inputSchema: {
    module_id: z2.string().uuid().describe("uuid do m\xF3dulo (use list_modules pra descobrir)"),
    content: z2.string().min(10).max(4e3).describe("texto da s\xEDntese/registro da entrega, 10 a 4000 caracteres"),
    link: z2.string().url().nullable().describe("link opcional do projeto/artefato. passe null se n\xE3o tiver")
  },
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: false
  },
  handler: async ({ module_id, content, link }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "n\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseAsUser(ctx);
    const { data, error } = await supabase.from("module_deliverables").insert({
      module_id,
      user_id: ctx.getUserId(),
      content,
      link,
      status: "submitted"
    }).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        { type: "text", text: `entrega registrada. id=${data.id}` }
      ],
      structuredContent: { deliverable: data }
    };
  }
});

// src/lib/mcp/tools/admin-list-at-risk.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var admin_list_at_risk_default = defineTool4({
  name: "admin_list_at_risk",
  title: "Admin: estudantes em risco",
  description: "S\xF3 admin. Lista alertas ativos de evas\xE3o / ativa\xE7\xE3o pendente. Usa `student_alerts` respeitando has_role(admin).",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "n\xE3o autenticado" }], isError: true };
    }
    if (!await isAdmin(ctx)) {
      return {
        content: [{ type: "text", text: "acesso negado: essa ferramenta \xE9 s\xF3 pra admin" }],
        isError: true
      };
    }
    const supabase = supabaseAsUser(ctx);
    const { data, error } = await supabase.from("student_alerts").select("id, user_id, alert_type, severity, reason, created_at, resolved_at").is("resolved_at", null).order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { alerts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jrzahsjrzaaktuelnsaw";
var mcp_default = defineMcp({
  name: "nachesu-mcp",
  title: "NachesU",
  version: "0.1.0",
  instructions: "Ferramentas da NachesU pra assistentes de IA. Use `get_my_progress` pra ver as eletivas do estudante logado, `list_modules` pra listar m\xF3dulos liberados de uma eletiva, `submit_evidence` pra registrar entregas em nome do estudante (requer aprova\xE7\xE3o) e `admin_list_at_risk` (s\xF3 admin) pra listar alertas ativos.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_progress_default, list_modules_default, submit_evidence_default, admin_list_at_risk_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
